### ISSUE TITLE
Craft install fails - nl is not a valid language.

### ISSUE THREAD

**Issue by SHoogland** [craftcms/docker#59] opened 2022-06-09 10:22 UTC
### Description
craft install fails due to missing locales
We use the cli image to install and test our craft site in github actions. 
It suddenly broke with this error:
Invalid arguments:
    - nl is not a valid language.

after some investigation this was due to the updated craftcms/cli:8.1 image

did something change/go wrong with the resource bundle in the latest image build?

### Steps to reproduce

1. try to run an install with the --language argument with the latest cli image
2. e.g. ```docker-compose run --rm craftcliservice php craft install/craft --email login@email.com --language nl --password password --site-name "Site (NL)" --site-url @siteUrl```

**Comment by thijskaspers** [comment] 2022-06-10 14:12
See https://github.com/craftcms/docker/issues/60#issuecomment-1152406306

**Comment by ballmannweber** [comment] 2022-06-11 17:42
I also can’t use Craft and nitro with our german language option which makes nitro pretty useless at the moment.

I checked for the discussion on "[8.x] Missing Locales #60" and even as I understand that it has to do with the Alpine Linux Version that comes with Docker I have no clue how to use the stated workaround ("downgrade/pin to Alpine Linux 3.15").

Anyone can help?

**Comment by fdelaneau** [comment] 2022-06-13 08:44
Using Nitro to create a new craft site, I was also unable to set French as the site language. I tried with the terminal using fr-FR and simply fr all option but the default resulted in an error message.

I then created a new install and tried to setup Craft from the browser and here are the only available choices :

<img width="816" alt="Capture d’écran 2022-06-13 à 10 13 10" src="https://user-images.githubusercontent.com/129808/173314899-3517ad27-a61d-41bd-bcd5-faec5e339d5c.png">

Note that once the installation is completed, the CP is available in all languages and can be changed per users as usual. The problem is only with the site “local” language where only English variants are available.

**Comment by thijskaspers** [comment] 2022-06-13 10:22
> I also can’t use Craft and nitro with our german language option which makes nitro pretty useless at the moment.
> 
> I checked for the discussion on "[8.x] Missing Locales #60" and even as I understand that it has to do with the Alpine Linux Version that comes with Docker I have no clue how to use the stated workaround ("downgrade/pin to Alpine Linux 3.15").
> 
> Anyone can help?

Sorry for the confusion. This is something that has to be fixed in the Dockerfile by the owner of this repo if you use nitro. I haven't had the time yet to create a pull request.

To clarify the 2 possible 'fixes' on the Dockerfile side of things:

**Option 1.** In the PHP Dockerfiles from this repo, there is a line: https://github.com/craftcms/docker/blob/9d8958193e8e43be3d30f1b17f2f6f130379df21/8.1/Dockerfile#L8 that could be changed to `FROM php:${PHP_VERSION}-${PROJECT_TYPE}-alpine3.15` to pin it to a fixed Alpine version that still has all locales installed by default.

**Option 2.** (this is probably the better option to stay up-to-date). If you want to keep using the latest Alpine version (3.16+), the following package `icu-data-full` has to be added to the list of all the packages in the Dockerfile, right where `icu-dev` is also located, see this part in the Dockerfile where all the required packages are installed:
https://github.com/craftcms/docker/blob/9d8958193e8e43be3d30f1b17f2f6f130379df21/8.1/Dockerfile#L51

**Closed** 2022-06-17 04:30 UTC
Labels: bug
